const SIZE=9, MINES=10; let cells, started=false, ended=false, flags=0, opened=0, seconds=0, timer;
const boardEl=document.querySelector('#board'), minesEl=document.querySelector('#mines'), timeEl=document.querySelector('#time'), messageEl=document.querySelector('#message');
function neighbors(i){const r=Math.floor(i/SIZE),c=i%SIZE, out=[];for(let dr=-1;dr<=1;dr++)for(let dc=-1;dc<=1;dc++){const nr=r+dr,nc=c+dc;if((dr||dc)&&nr>=0&&nr<SIZE&&nc>=0&&nc<SIZE)out.push(nr*SIZE+nc)}return out}
function placeMines(safe){const blocked=new Set([safe,...neighbors(safe)]);let placed=0;while(placed<MINES){const i=Math.floor(Math.random()*SIZE*SIZE);if(!blocked.has(i)&&!cells[i].mine){cells[i].mine=true;placed++}}cells.forEach((cell,i)=>cell.count=neighbors(i).filter(n=>cells[n].mine).length)}
function draw(){boardEl.replaceChildren();cells.forEach((cell,i)=>{const b=document.createElement('button');b.className=`cell${cell.open?' open':''}${cell.flag?' flag':''}${cell.open&&cell.mine?' mine':''}`;b.type='button';b.textContent=cell.open?(cell.mine?'💣':cell.count||''):cell.flag?'⚑':'';b.addEventListener('click',()=>open(i));let hold; b.addEventListener('pointerdown',e=>{hold=setTimeout(()=>{flag(i);hold=null},500)});b.addEventListener('pointerup',()=>clearTimeout(hold));b.addEventListener('pointerleave',()=>clearTimeout(hold));boardEl.append(b)});minesEl.textContent=`💣 ${MINES-flags}`;timeEl.textContent=`⏱ ${seconds}`}
function open(i){if(ended||cells[i].flag)return;if(!started){started=true;placeMines(i);timer=setInterval(()=>{seconds++;timeEl.textContent=`⏱ ${seconds}`},1000);messageEl.textContent='地雷を避けよう！'}const cell=cells[i];if(cell.open)return;cell.open=true;if(cell.mine){end(false);return}opened++;if(!cell.count)neighbors(i).forEach(n=>{if(!cells[n].open)open(n)});if(opened===SIZE*SIZE-MINES)end(true);draw()}
function flag(i){if(ended||cells[i].open)return;cells[i].flag=!cells[i].flag;flags+=cells[i].flag?1:-1;draw()}
function end(win){ended=true;clearInterval(timer);if(!win)cells.forEach(c=>{if(c.mine)c.open=true});draw();document.querySelector('#result').textContent=win?`${seconds}秒でクリア！`:'地雷に当たりました';document.querySelector('#dialog').hidden=false}
function reset(){clearInterval(timer);cells=Array.from({length:SIZE*SIZE},()=>({mine:false,count:0,open:false,flag:false}));started=ended=false;flags=opened=seconds=0;messageEl.textContent='マスをタップして開始';document.querySelector('#dialog').hidden=true;draw()}
document.querySelector('#restart').onclick=reset;document.querySelector('#again').onclick=reset;reset();
