const EMPTY = 0, BLACK = 1, WHITE = -1;
const directions = [[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
let board, currentPlayer, gameOver = false, cpuTimer;
const boardEl = document.querySelector('#board'), messageEl = document.querySelector('#turn-message'), hintEl = document.querySelector('#hint');

function newBoard() { const b = Array.from({length:8}, () => Array(8).fill(EMPTY)); b[3][3]=WHITE; b[3][4]=BLACK; b[4][3]=BLACK; b[4][4]=WHITE; return b; }
function inside(r,c) { return r >= 0 && r < 8 && c >= 0 && c < 8; }
function flipsFor(r,c,player,source=board) { if (source[r][c] !== EMPTY) return []; const flips=[]; for (const [dr,dc] of directions) { const line=[]; let nr=r+dr,nc=c+dc; while(inside(nr,nc) && source[nr][nc] === -player) { line.push([nr,nc]); nr+=dr; nc+=dc; } if(line.length && inside(nr,nc) && source[nr][nc] === player) flips.push(...line); } return flips; }
function legalMoves(player, source=board) { const moves=[]; for(let r=0;r<8;r++) for(let c=0;c<8;c++) { const flips=flipsFor(r,c,player,source); if(flips.length) moves.push({r,c,flips}); } return moves; }
function count() { let black=0,white=0; board.flat().forEach(v => v===BLACK ? black++ : v===WHITE ? white++ : 0); return {black,white}; }
function render() { const legal = currentPlayer === BLACK && !gameOver ? new Map(legalMoves(BLACK).map(m=>[`${m.r},${m.c}`,m])) : new Map(); boardEl.replaceChildren(); board.forEach((row,r)=>row.forEach((value,c)=>{ const cell=document.createElement('button'); cell.className='cell'; cell.type='button'; cell.setAttribute('role','gridcell'); const move=legal.get(`${r},${c}`); if(move) { cell.classList.add('legal'); cell.setAttribute('aria-label',`${r+1}行${c+1}列に置く`); cell.addEventListener('click',()=>playMove(move)); } else cell.setAttribute('aria-label',`${r+1}行${c+1}列`); if(value) { const disc=document.createElement('span'); disc.className=`disc ${value===BLACK?'black':'white'}`; cell.append(disc); } boardEl.append(cell); })); const {black,white}=count(); document.querySelector('#black-score').textContent=black; document.querySelector('#white-score').textContent=white; }
function applyMove(move,player) { board[move.r][move.c]=player; move.flips.forEach(([r,c])=>board[r][c]=player); }
function playMove(move) { if(gameOver || currentPlayer !== BLACK) return; applyMove(move,BLACK); currentPlayer=WHITE; messageEl.textContent='CPUが考え中…'; hintEl.textContent='少しお待ちください'; render(); cpuTimer=setTimeout(cpuTurn,420); }
function chooseCpuMove(moves) { return moves.map(move=>{ let score=move.flips.length*8; const corner=(move.r===0||move.r===7)&&(move.c===0||move.c===7); const edge=move.r===0||move.r===7||move.c===0||move.c===7; if(corner) score+=1000; else if(edge) score+=35; const next=board.map(row=>[...row]); next[move.r][move.c]=WHITE; move.flips.forEach(([r,c])=>next[r][c]=WHITE); score-=legalMoves(BLACK,next).length*4; return {...move,score}; }).sort((a,b)=>b.score-a.score)[0]; }
function cpuTurn() { if(gameOver) return; const moves=legalMoves(WHITE); if(!moves.length) { changeTurnOrFinish('CPUは置けないためパスしました'); return; } applyMove(chooseCpuMove(moves),WHITE); currentPlayer=BLACK; changeTurnOrFinish(); }
function changeTurnOrFinish(prefix='') { const moves=legalMoves(currentPlayer); const opponentMoves=legalMoves(-currentPlayer); if(!moves.length && !opponentMoves.length) return finish(); if(!moves.length) { const passer=currentPlayer===BLACK?'あなた':'CPU'; currentPlayer=-currentPlayer; const text=`${prefix ? `${prefix}　` : ''}${passer}は置けないためパスしました`; messageEl.textContent=text; hintEl.textContent='相手の番です'; render(); if(currentPlayer===WHITE) cpuTimer=setTimeout(cpuTurn,650); return; } if(currentPlayer===BLACK) { messageEl.textContent=prefix || 'あなたの番です'; hintEl.textContent='光っているマスをタップしてください'; render(); } else { messageEl.textContent='CPUが考え中…'; hintEl.textContent='少しお待ちください'; render(); cpuTimer=setTimeout(cpuTurn,420); } }
function finish() { gameOver=true; clearTimeout(cpuTimer); render(); const {black,white}=count(); const title=black===white?'引き分け！':black>white?'あなたの勝ち！':'CPUの勝ち'; messageEl.textContent='ゲーム終了'; hintEl.textContent='最初から遊ぶで再戦できます'; document.querySelector('#result-title').textContent=title; document.querySelector('#result-score').innerHTML=`あなた <strong>${black}</strong> − <strong>${white}</strong> CPU`; document.querySelector('#result-dialog').hidden=false; }
function restart() { clearTimeout(cpuTimer); board=newBoard(); currentPlayer=BLACK; gameOver=false; document.querySelector('#result-dialog').hidden=true; messageEl.textContent='あなたの番です'; hintEl.textContent='光っているマスをタップしてください'; render(); }
document.querySelector('#restart').addEventListener('click',restart); document.querySelector('#play-again').addEventListener('click',restart); restart();
