const SIZE=4, MOVE_MS=170, MERGE_MS=300;
let tiles=[],score=0,best=Number(localStorage.getItem('2048-best')||0),nextId=1,busy=false,won=false,touchStart=null,queuedDirection=null;
const tilesEl=document.querySelector('#tiles'),effectsEl=document.querySelector('#effects'),scoreEl=document.querySelector('#score'),bestEl=document.querySelector('#best');
document.querySelector('.grid').innerHTML='<i></i>'.repeat(16);

function color(v){const c={2:'#eee4da',4:'#ede0c8',8:'#f2b179',16:'#f59563',32:'#f67c5f',64:'#f65e3b',128:'#edcf72',256:'#edcc61',512:'#edc850',1024:'#edc53f',2048:'#edc22e'};return c[v]||'#3c3a32'}
function addTile(){const empty=[];for(let r=0;r<SIZE;r++)for(let c=0;c<SIZE;c++)if(!tiles.some(t=>t.r===r&&t.c===c))empty.push([r,c]);if(!empty.length)return;const [r,c]=empty[Math.floor(Math.random()*empty.length)];tiles.push({id:nextId++,value:Math.random()<.9?2:4,r,c,spawn:true})}
function render(){const ids=new Set;tiles.forEach(t=>{ids.add(String(t.id));let el=tilesEl.querySelector(`[data-id="${t.id}"]`);if(!el){el=document.createElement('div');el.className='tile';el.dataset.id=t.id;el.innerHTML='<span></span>';tilesEl.append(el)}el.style.setProperty('--tx',`${t.c*100}%`);el.style.setProperty('--ty',`${t.r*100}%`);el.style.setProperty('--color',color(t.value));el.style.setProperty('--text',t.value<=4?'#776e65':'#fff');el.querySelector('span').textContent=t.displayValue??t.value;el.classList.toggle('spawn',!!t.spawn);el.classList.toggle('merge',!!t.merge)});tilesEl.querySelectorAll('.tile').forEach(el=>{if(!ids.has(el.dataset.id))el.remove()});scoreEl.textContent=score;best=Math.max(best,score);bestEl.textContent=best;localStorage.setItem('2048-best',best)}
function effect(t,value){const left=`${(t.c+.5)*25}%`,top=`${(t.r+.5)*25}%`;const p=document.createElement('b');p.className='points';p.textContent=`+${value}`;p.style.left=left;p.style.top=top;effectsEl.append(p);setTimeout(()=>p.remove(),720);for(let i=0;i<10;i++){const s=document.createElement('i');s.className='spark';s.style.left=left;s.style.top=top;s.style.setProperty('--a',`${i*36}deg`);s.style.setProperty('--distance',`${34+Math.random()*22}px`);effectsEl.append(s);setTimeout(()=>s.remove(),620)}}
function move(dr,dc){const ordered=[...tiles].sort((a,b)=>dc?(dc>0?b.c-a.c:a.c-b.c):(dr>0?b.r-a.r:a.r-b.r));const grid=Array.from({length:SIZE},()=>Array(SIZE).fill(null));tiles.forEach(t=>grid[t.r][t.c]=t);let changed=false;const merges=[];
  ordered.forEach(t=>{grid[t.r][t.c]=null;const startR=t.r,startC=t.c;let r=t.r,c=t.c;while(r+dr>=0&&r+dr<SIZE&&c+dc>=0&&c+dc<SIZE&&!grid[r+dr][c+dc]){r+=dr;c+=dc}const target=(r+dr>=0&&r+dr<SIZE&&c+dc>=0&&c+dc<SIZE)?grid[r+dr][c+dc]:null;if(target&&target.value===t.value&&!target.mergedThisMove){t.r=target.r;t.c=target.c;t.remove=true;target.displayValue=target.value;target.value*=2;target.mergedThisMove=true;score+=target.value;merges.push(target)}else{t.r=r;t.c=c;grid[r][c]=t}if(t.r!==startR||t.c!==startC)changed=true});
  if(!changed){tiles.forEach(t=>delete t.mergedThisMove);busy=false;runQueued();return}
  busy=true;render();
  setTimeout(()=>{tiles=tiles.filter(t=>!t.remove);merges.forEach(t=>{delete t.displayValue;t.merge=true;effect(t,t.value)});if(merges.length&&navigator.vibrate)navigator.vibrate(25);addTile();render();tiles.forEach(t=>t.spawn=false);if(!won&&tiles.some(t=>t.value>=2048)){won=true;showDialog('2048達成！',false)}else if(!canMove())showDialog('ゲーム終了',true)},MOVE_MS);
  setTimeout(()=>{tiles.forEach(t=>{t.merge=false;delete t.mergedThisMove});render();busy=false;runQueued()},MOVE_MS+MERGE_MS)
}
function prepareMove(dr,dc){if(busy){queuedDirection=[dr,dc];return}move(dr,dc)}
function runQueued(){if(!queuedDirection||busy)return;const direction=queuedDirection;queuedDirection=null;requestAnimationFrame(()=>prepareMove(...direction))}
function canMove(){if(tiles.length<SIZE*SIZE)return true;return tiles.some(t=>[[1,0],[0,1]].some(([dr,dc])=>tiles.some(u=>u.r===t.r+dr&&u.c===t.c+dc&&u.value===t.value)))}
function showDialog(title,gameOver){document.querySelector('#result').textContent=title;document.querySelector('#final-score').textContent=`スコア ${score}`;document.querySelector('#dialog').hidden=false;if(!gameOver)setTimeout(()=>document.querySelector('#dialog').hidden=true,1100)}
function reset(){tiles=[];score=0;won=false;busy=false;queuedDirection=null;document.querySelector('#dialog').hidden=true;addTile();addTile();render();requestAnimationFrame(()=>{tiles.forEach(t=>t.spawn=false)})}
document.addEventListener('keydown',e=>{const d={ArrowUp:[-1,0],ArrowDown:[1,0],ArrowLeft:[0,-1],ArrowRight:[0,1]}[e.key];if(d){e.preventDefault();prepareMove(...d)}});
const board=document.querySelector('#board');board.addEventListener('pointerdown',e=>touchStart=[e.clientX,e.clientY]);board.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart[0],dy=e.clientY-touchStart[1];touchStart=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;prepareMove(...(Math.abs(dx)>Math.abs(dy)?[0,Math.sign(dx)]:[Math.sign(dy),0]))});board.addEventListener('pointercancel',()=>touchStart=null);
document.querySelector('#restart').onclick=reset;document.querySelector('#again').onclick=reset;reset();
