const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),arena=document.querySelector('#arena');
const ui={level:document.querySelector('#level'),time:document.querySelector('#time'),kills:document.querySelector('#kills'),score:document.querySelector('#score'),best:document.querySelector('#best'),hp:document.querySelector('#hp-bar'),hpText:document.querySelector('#hp-text'),xp:document.querySelector('#xp-bar'),xpText:document.querySelector('#xp-text'),loadout:document.querySelector('#loadout-list'),pause:document.querySelector('#pause'),paused:document.querySelector('#paused-panel'),start:document.querySelector('#start-panel'),upgrade:document.querySelector('#upgrade-dialog'),upgradeList:document.querySelector('#upgrade-list'),reroll:document.querySelector('#reroll'),reward:document.querySelector('#reward-dialog'),rewardTitle:document.querySelector('#reward-title'),rewardList:document.querySelector('#reward-list'),result:document.querySelector('#result-dialog'),bossAlert:document.querySelector('#boss-alert'),stick:document.querySelector('#stick')};
const GAME_LENGTH=600,MAX_ENEMIES=180,MAX_PROJECTILES=120,MAX_ORBS=400,MAX_PARTICLES=140,MAX_WEAPONS=4,MAX_ABILITIES=4,GRID_SIZE=96;
const ENEMY_TYPES={
  slime:{hp:20,speed:42,radius:15,damage:10,xp:4,color:'#58d68d',score:10},
  bat:{hp:12,speed:78,radius:11,damage:8,xp:4,color:'#bf74ff',score:14},
  golem:{hp:75,speed:27,radius:21,damage:16,xp:9,color:'#a48165',score:30},
  elite:{hp:390,speed:36,radius:29,damage:22,xp:35,color:'#ff8b51',score:500},
  boss:{hp:3000,speed:31,radius:43,damage:30,xp:100,color:'#ff426d',score:5000}
};
const UPGRADES={
  magic:{name:'魔法弾',symbol:'✦',kind:'weapon',max:5,desc:'弾数・威力・貫通を強化'},
  orbit:{name:'回転刃',symbol:'◈',kind:'weapon',max:5,desc:'周囲を回る刃を追加'},
  lightning:{name:'雷撃',symbol:'ϟ',kind:'weapon',max:5,desc:'複数の敵へ落雷'},
  fire:{name:'炎の輪',symbol:'◉',kind:'weapon',max:5,desc:'周囲へ継続ダメージ'},
  arrow:{name:'貫通矢',symbol:'➵',kind:'weapon',max:5,desc:'移動方向へ貫通攻撃'},
  ice:{name:'氷結波',symbol:'❄',kind:'weapon',max:5,desc:'周囲を攻撃して減速'},
  holy:{name:'聖なる光',symbol:'☀',kind:'weapon',max:5,desc:'画面全体を定期攻撃'},
  power:{name:'攻撃力',symbol:'⚔',kind:'ability',max:5,desc:'すべてのダメージ +18%'},
  speed:{name:'移動速度',symbol:'➤',kind:'ability',max:5,desc:'移動速度 +10%'},
  cooldown:{name:'攻撃速度',symbol:'⌛',kind:'ability',max:5,desc:'攻撃間隔を8%短縮'},
  range:{name:'攻撃範囲',symbol:'◌',kind:'ability',max:5,desc:'攻撃範囲 +12%'},
  magnet:{name:'吸引範囲',symbol:'◎',kind:'ability',max:5,desc:'経験値の取得範囲を拡大'},
  vitality:{name:'最大HP',symbol:'♥',kind:'ability',max:5,desc:'最大HP +20、HPを回復'},
  regen:{name:'自動回復',symbol:'✚',kind:'ability',max:5,desc:'HPを徐々に回復'},
  defense:{name:'防御力',symbol:'⬟',kind:'ability',max:5,desc:'受けるダメージ -8%'}
};
const EVOLUTIONS={
  magic:{ability:'power',name:'星砕きの魔弾',symbol:'✹',desc:'弾数と貫通が大幅に増加'},
  orbit:{ability:'defense',name:'守護輪刃',symbol:'✥',desc:'巨大な刃が周囲を守る'},
  lightning:{ability:'cooldown',name:'天雷連鎖',symbol:'ϟ',desc:'多数の敵へ強力な連鎖雷撃'},
  fire:{ability:'range',name:'獄炎結界',symbol:'◉',desc:'広大な炎域で敵を焼き続ける'},
  arrow:{ability:'speed',name:'幻影連弩',symbol:'➵',desc:'大量の矢が敵を貫く'},
  ice:{ability:'magnet',name:'絶対零域',symbol:'❆',desc:'広範囲を凍結して強く減速'},
  holy:{ability:'regen',name:'暁の聖域',symbol:'☼',desc:'聖光が敵を焼きHPも回復'}
};
const ITEMS={heal:{symbol:'✚',name:'回復薬',color:'#72efa5'},magnet:{symbol:'◎',name:'磁石',color:'#9f87ff'},bomb:{symbol:'✹',name:'爆弾',color:'#ff855f'},clock:{symbol:'◷',name:'時計',color:'#72dfff'},chest:{symbol:'◆',name:'宝箱',color:'#ffd56a'}};
const projectilePool=[],particlePool=[];
let enemyGrid=new Map(),state,input,keys={},pointerId=null,stickOrigin={x:0,y:0},lastTime=0,raf=0;

function freshState(){return {running:false,paused:false,ended:false,time:0,kills:0,eliteKills:0,score:0,level:1,xp:0,nextXp:24,player:{x:0,y:0,radius:15,hp:100,maxHp:100,speed:150,invulnerable:0},levels:{magic:1,orbit:0,lightning:0,fire:0,arrow:0,ice:0,holy:0,power:0,speed:0,cooldown:0,range:0,magnet:0,vitality:0,regen:0,defense:0},evolved:{},enemies:[],projectiles:[],orbs:[],drops:[],particles:[],floaters:[],rings:[],timers:{magic:0,lightning:1,arrow:.4,ice:1.5,holy:3},spawnTimer:0,eliteAt:45,nextWave:24,bossSpawned:false,boss:null,freeze:0,screenShake:0,frame:0,uiTimer:0,lastDir:{x:0,y:-1},rerolls:0,lastChoices:[]};}
function reset(){cancelAnimationFrame(raf);state=freshState();input={x:0,y:0};lastTime=0;ui.result.hidden=true;ui.upgrade.hidden=true;ui.reward.hidden=true;ui.paused.hidden=true;ui.start.hidden=false;ui.bossAlert.hidden=true;ui.pause.textContent='Ⅱ';ui.best.textContent=Number(localStorage.getItem('night-survivor-best')||0);resize();renderLoadout();updateUI();draw();}
function resize(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);}
function screen(){return {w:canvas.clientWidth,h:canvas.clientHeight};}
function start(){if(state.running)return;state.running=true;state.paused=false;ui.start.hidden=true;lastTime=performance.now();raf=requestAnimationFrame(loop);}
function togglePause(force){if(!state.running||state.ended||!ui.upgrade.hidden)return;state.paused=force===undefined?!state.paused:force;ui.paused.hidden=!state.paused;ui.pause.textContent=state.paused?'▶':'Ⅱ';if(!state.paused){lastTime=performance.now();raf=requestAnimationFrame(loop);}else cancelAnimationFrame(raf);}
function loop(now){if(!state.running||state.paused||state.ended)return;const dt=Math.min(.04,(now-lastTime)/1000||0);lastTime=now;update(dt);draw();if(!state.ended&&!state.paused)raf=requestAnimationFrame(loop);}
function moveVector(){let x=input.x+(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0),y=input.y+(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);const length=Math.hypot(x,y);return length>1?{x:x/length,y:y/length}:{x,y};}
function update(dt){
  state.frame++;state.time+=dt;state.freeze=Math.max(0,state.freeze-dt);const p=state.player,v=moveVector(),speed=p.speed*(1+state.levels.speed*.1);p.x+=v.x*speed*dt;p.y+=v.y*speed*dt;if(Math.hypot(v.x,v.y)>.2)state.lastDir={x:v.x,y:v.y};p.invulnerable=Math.max(0,p.invulnerable-dt);p.hp=Math.min(p.maxHp,p.hp+state.levels.regen*.45*dt);state.screenShake=Math.max(0,state.screenShake-dt);
  const phase=Math.min(5,Math.floor(state.time/120));state.spawnTimer-=dt;if(state.spawnTimer<=0&&state.enemies.length<MAX_ENEMIES&&!state.bossSpawned){const amount=1+Math.floor(phase/2);for(let i=0;i<amount;i++)spawnEnemy(pickEnemyType(phase));state.spawnTimer=Math.max(.14,.7-phase*.08);}
  if(state.time>=state.nextWave&&state.time<GAME_LENGTH&&!state.bossSpawned){spawnPattern();state.nextWave+=Math.max(15,24-phase*1.5);}
  if(state.time>=state.eliteAt&&state.time<GAME_LENGTH&&!state.bossSpawned){spawnEnemy('elite');state.eliteAt+=70;showAlert('⚠ エリート出現 ⚠',1200);}
  if(state.time>=GAME_LENGTH&&!state.bossSpawned){state.bossSpawned=true;state.enemies=state.enemies.filter(e=>e.type==='elite');state.boss=spawnEnemy('boss');showAlert('⚠ BOSS APPROACHING ⚠',2200);}
  activateVisibleEnemies();buildEnemyGrid();updateWeapons(dt);updateProjectiles(dt);updateEnemies(dt);updateOrbs(dt);updateDrops();updateEffects(dt);state.uiTimer-=dt;if(state.uiTimer<=0){updateUI();state.uiTimer=.1;}
}
function pickEnemyType(phase){const r=Math.random();if(phase<1)return r<.78?'slime':'bat';if(phase<3)return r<.5?'slime':r<.8?'bat':'golem';return r<.32?'slime':r<.65?'bat':'golem';}
function normalHpScale(){return (1+state.time/60*.4)**2;}
function spawnEnemy(type,position){if(state.enemies.length>=MAX_ENEMIES)return null;const {w,h}=screen(),angle=Math.random()*Math.PI*2,distance=Math.hypot(w,h)*.62+60,t=ENEMY_TYPES[type],minutes=state.time/60,isNormal=type!=='boss'&&type!=='elite',champion=isNormal&&Math.random()<Math.min(.25,.1+minutes*.015),scale=type==='boss'?1:type==='elite'?1+minutes*.12:normalHpScale(),championHp=champion?5:1,pos=position||{x:state.player.x+Math.cos(angle)*distance,y:state.player.y+Math.sin(angle)*distance};const maxHp=t.hp*scale*championHp,enemy={type,x:pos.x,y:pos.y,hp:maxHp,maxHp,speed:t.speed*(1+Math.min(.5,state.time/900))*(champion?1.08:1),radius:t.radius*(champion?1.18:1),damage:t.damage*(champion?1.5:1),rewardXp:t.xp*(champion?3:1),rewardScore:t.score*(champion?4:1),champion,attackable:false,orbitHit:-9,fireHit:-9,slow:0,color:t.color};state.enemies.push(enemy);return enemy;}
function spawnPattern(){const p=state.player,{w,h}=screen(),radius=Math.hypot(w,h)*.62+70,phase=Math.min(5,Math.floor(state.time/120)),type=pickEnemyType(phase),pattern=Math.floor(Math.random()*4);if(pattern===0){for(let i=0;i<10;i++){const a=i*Math.PI*2/10;spawnEnemy(type,{x:p.x+Math.cos(a)*radius,y:p.y+Math.sin(a)*radius});}showAlert('包囲網！',850);}else if(pattern===1){const a=Math.random()*Math.PI*2,tx=-Math.sin(a),ty=Math.cos(a);for(let i=-5;i<=5;i++)spawnEnemy(type,{x:p.x+Math.cos(a)*radius+tx*i*42,y:p.y+Math.sin(a)*radius+ty*i*42});showAlert('敵の大群が接近！',850);}else if(pattern===2){for(let i=0;i<14;i++){const a=i*Math.PI*2/14;spawnEnemy(type,{x:p.x+Math.cos(a)*radius,y:p.y+Math.sin(a)*radius});}showAlert('円形包囲！',850);}else{const a=Math.random()*Math.PI*2,tx=-Math.sin(a),ty=Math.cos(a);for(let i=-7;i<=7;i++){if(Math.abs(i)<=1)continue;spawnEnemy(type,{x:p.x+Math.cos(a)*radius+tx*i*36,y:p.y+Math.sin(a)*radius+ty*i*36});}showAlert('敵壁に隙間を発見！',850);}}
function gridKey(x,y){return `${Math.floor(x/GRID_SIZE)}/${Math.floor(y/GRID_SIZE)}`;}
function activateVisibleEnemies(){const {w,h}=screen(),p=state.player;for(const e of state.enemies){if(e.attackable)continue;const x=e.x-p.x+w/2,y=e.y-p.y+h/2;if(x>=0&&x<=w&&y>=0&&y<=h)e.attackable=true;}}
function buildEnemyGrid(){enemyGrid=new Map();for(const e of state.enemies){if(!e.attackable)continue;const key=gridKey(e.x,e.y);if(!enemyGrid.has(key))enemyGrid.set(key,[]);enemyGrid.get(key).push(e);}}
function nearbyEnemies(x,y,radius){const found=[],minX=Math.floor((x-radius)/GRID_SIZE),maxX=Math.floor((x+radius)/GRID_SIZE),minY=Math.floor((y-radius)/GRID_SIZE),maxY=Math.floor((y+radius)/GRID_SIZE);for(let gx=minX;gx<=maxX;gx++)for(let gy=minY;gy<=maxY;gy++){const bucket=enemyGrid.get(`${gx}/${gy}`);if(bucket)found.push(...bucket);}return found;}
function cooldownFactor(){return Math.max(.55,1-state.levels.cooldown*.08)}function powerFactor(){return 1+state.levels.power*.18}function rangeFactor(){return 1+state.levels.range*.12}
function weaponRange(key){const l=state.levels[key],bases={magic:300+l*35,arrow:450+l*38,lightning:230+l*32,orbit:54+l*7,fire:56+l*10,ice:105+l*18},base=key==='holy'?Math.hypot(screen().w,screen().h)*(.52+l*.035):bases[key],evolved=state.evolved[key]?(key==='fire'||key==='ice'?1.28:1.16):1;return base*rangeFactor()*evolved;}
function addProjectile(data){if(state.projectiles.length>=MAX_PROJECTILES)return;state.projectiles.push(Object.assign(projectilePool.pop()||{},data));}
function updateWeapons(dt){
  const p=state.player,t=state.timers,l=state.levels;t.magic-=dt;if(t.magic<=0){const evolved=state.evolved.magic,count=1+Math.floor((l.magic-1)/2)+(evolved?2:0),range=weaponRange('magic');nearestEnemies(count,range).forEach((enemy,i)=>{const a=Math.atan2(enemy.y-p.y,enemy.x-p.x)+(i-(count-1)/2)*.08;addProjectile({x:p.x,y:p.y,vx:Math.cos(a)*380,vy:Math.sin(a)*380,radius:evolved?7:5,damage:(13+l.magic*6)*powerFactor()*(evolved?1.45:1),life:3,pierce:(l.magic>=4?2:1)+(evolved?2:0),rangeRemaining:range,color:evolved?'#ffe896':'#d8c4ff'});});t.magic=(.72-l.magic*.055)*cooldownFactor();}
  if(l.arrow){t.arrow-=dt;if(t.arrow<=0){let dir=state.lastDir;const range=weaponRange('arrow'),target=nearestEnemies(1,range)[0];if(Math.hypot(dir.x,dir.y)<.2&&target){const d=Math.hypot(target.x-p.x,target.y-p.y)||1;dir={x:(target.x-p.x)/d,y:(target.y-p.y)/d};}const evolved=state.evolved.arrow,count=1+Math.floor((l.arrow-1)/2)+(evolved?2:0);for(let i=0;i<count;i++){const base=Math.atan2(dir.y,dir.x)+(i-(count-1)/2)*.13;addProjectile({x:p.x,y:p.y,vx:Math.cos(base)*520,vy:Math.sin(base)*520,radius:evolved?5:4,damage:(18+l.arrow*7)*powerFactor()*(evolved?1.35:1),life:3,pierce:1+l.arrow+(evolved?3:0),rangeRemaining:range,color:evolved?'#ff9af0':'#ffd76a'});}t.arrow=(1.2-l.arrow*.08)*cooldownFactor();}}
  if(l.lightning){t.lightning-=dt;if(t.lightning<=0){const evolved=state.evolved.lightning,count=1+l.lightning+(evolved?3:0);nearestEnemies(count,weaponRange('lightning')).forEach(e=>{damageEnemy(e,(24+l.lightning*13)*powerFactor()*(evolved?1.4:1));burst(e.x,e.y,evolved?'#fff18c':'#89eaff',evolved?12:8);state.floaters.push({x:e.x,y:e.y,text:'ϟ',color:'#bdf5ff',life:.55});});t.lightning=(2.4-l.lightning*.18)*(evolved?.78:1)*cooldownFactor();}}
  if(l.orbit){const evolved=state.evolved.orbit,blades=1+l.orbit+(evolved?2:0),range=weaponRange('orbit'),now=state.time*(evolved?2.8:2.2);for(const e of nearbyEnemies(p.x,p.y,range+35)){for(let i=0;i<blades;i++){const a=now+i*Math.PI*2/blades,bx=p.x+Math.cos(a)*range,by=p.y+Math.sin(a)*range;if(Math.hypot(e.x-bx,e.y-by)<e.radius+(evolved?14:10)&&state.time-e.orbitHit>.35){e.orbitHit=state.time;damageEnemy(e,(8+l.orbit*5)*powerFactor()*(evolved?1.4:1));break;}}}}
  if(l.fire){const evolved=state.evolved.fire,radius=weaponRange('fire');for(const e of nearbyEnemies(p.x,p.y,radius+35))if(Math.hypot(e.x-p.x,e.y-p.y)<radius+e.radius&&state.time-e.fireHit>.42){e.fireHit=state.time;damageEnemy(e,(5+l.fire*3)*powerFactor()*(evolved?1.5:1));}}
  if(l.ice){t.ice-=dt;if(t.ice<=0){const evolved=state.evolved.ice,radius=weaponRange('ice');for(const e of nearbyEnemies(p.x,p.y,radius+40))if(Math.hypot(e.x-p.x,e.y-p.y)<=radius+e.radius){damageEnemy(e,(12+l.ice*7)*powerFactor()*(evolved?1.4:1));e.slow=evolved?3.4:2.2;}ring(p.x,p.y,radius,evolved?'#dffaff':'#8de8ff');t.ice=(3.4-l.ice*.18)*(evolved?.78:1)*cooldownFactor();}}
  if(l.holy){t.holy-=dt;if(t.holy<=0){const evolved=state.evolved.holy,radius=weaponRange('holy');for(const e of state.enemies)if(e.attackable&&Math.hypot(e.x-p.x,e.y-p.y)<radius)damageEnemy(e,(20+l.holy*12)*powerFactor()*(evolved?1.5:1));if(evolved)p.hp=Math.min(p.maxHp,p.hp+4);ring(p.x,p.y,radius,evolved?'#fffbd1':'#fff0a6');t.holy=(7-l.holy*.45)*(evolved?.8:1)*cooldownFactor();}}
}
function nearestEnemies(count,maxRange=Infinity){const limit=maxRange*maxRange;return state.enemies.filter(e=>e.attackable&&e.hp>0&&dist2(e,state.player)<=limit).sort((a,b)=>dist2(a,state.player)-dist2(b,state.player)).slice(0,count)}function dist2(a,b){return (a.x-b.x)**2+(a.y-b.y)**2}
function updateProjectiles(dt){for(const shot of state.projectiles){const travel=Math.hypot(shot.vx,shot.vy)*dt;shot.x+=shot.vx*dt;shot.y+=shot.vy*dt;shot.life-=dt;shot.rangeRemaining-=travel;if(shot.rangeRemaining<=0)shot.life=0;for(const e of nearbyEnemies(shot.x,shot.y,35)){if(e.hp<=0||shot.life<=0)continue;if(Math.hypot(e.x-shot.x,e.y-shot.y)<e.radius+shot.radius){damageEnemy(e,shot.damage);shot.pierce--;if(shot.pierce<=0)shot.life=0;}}}state.projectiles=state.projectiles.filter(shot=>{if(shot.life>0)return true;projectilePool.push(shot);return false;});}
function updateEnemies(dt){const p=state.player,{w,h}=screen(),far=Math.hypot(w,h)*.85;for(const e of state.enemies){e.slow=Math.max(0,e.slow-dt);const dx=p.x-e.x,dy=p.y-e.y,d=Math.hypot(dx,dy)||1;if(state.freeze>0)continue;if(d>far&&state.frame%2)continue;const step=d>far?dt*2:dt,mult=e.slow>0?(state.evolved.ice?.32:.52):1;e.x+=dx/d*e.speed*mult*step;e.y+=dy/d*e.speed*mult*step;if(d<e.radius+p.radius&&p.invulnerable<=0){const reduction=Math.min(.5,state.levels.defense*.08);p.hp=Math.max(0,p.hp-e.damage*(1-reduction));p.invulnerable=.65;state.screenShake=.18;burst(p.x,p.y,'#ff5671',12);if(!p.hp){finish(false);return;}}}state.enemies=state.enemies.filter(e=>e.hp>0);}
function damageEnemy(enemy,amount){if(!enemy.attackable||enemy.hp<=0)return;enemy.hp-=amount;state.floaters.push({x:enemy.x,y:enemy.y-10,text:Math.round(amount),color:'#ffe5a5',life:.55});if(enemy.hp<=0){state.kills++;if(enemy.type==='elite')state.eliteKills++;state.score+=enemy.rewardScore;addOrb(enemy.x,enemy.y,enemy.rewardXp);maybeDrop(enemy);burst(enemy.x,enemy.y,enemy.champion?'#ffd76a':enemy.color,enemy.type==='boss'?30:enemy.champion?14:7);if(enemy.type==='boss')finish(true);}}
function addOrb(x,y,value){if(state.orbs.length<MAX_ORBS)state.orbs.push({x,y,value,radius:5});else state.orbs[state.orbs.length-1].value+=value;}
function maybeDrop(enemy){if(enemy.type==='boss')return;if(enemy.type==='elite')state.drops.push({type:'chest',x:enemy.x,y:enemy.y});else if(Math.random()<.045&&state.drops.length<30){const types=['heal','magnet','bomb','clock'];state.drops.push({type:types[Math.floor(Math.random()*types.length)],x:enemy.x,y:enemy.y});}}
function updateOrbs(dt){const p=state.player,range=75+state.levels.magnet*34;for(const orb of state.orbs){const d=Math.hypot(p.x-orb.x,p.y-orb.y);if(d<range){const speed=110+(range-d)*5;orb.x+=(p.x-orb.x)/(d||1)*speed*dt;orb.y+=(p.y-orb.y)/(d||1)*speed*dt;}if(d<p.radius+10){orb.collected=true;gainXp(orb.value);}}state.orbs=state.orbs.filter(o=>!o.collected&&Math.hypot(p.x-o.x,p.y-o.y)<1400);}
function updateDrops(){const p=state.player;for(const drop of state.drops)if(Math.hypot(p.x-drop.x,p.y-drop.y)<p.radius+17){drop.collected=true;applyItem(drop.type);}state.drops=state.drops.filter(d=>!d.collected&&Math.hypot(p.x-d.x,p.y-d.y)<1400);}
function applyItem(type){const p=state.player;if(type==='chest'){openChest();return;}if(type==='heal')p.hp=Math.min(p.maxHp,p.hp+35);if(type==='magnet'){const total=state.orbs.reduce((sum,o)=>sum+o.value,0);state.orbs=[];gainXp(total);}if(type==='bomb')for(const e of state.enemies.filter(e=>e.attackable))damageEnemy(e,e.type==='boss'?240:260);if(type==='clock')state.freeze=Math.max(state.freeze,4);showAlert(`${ITEMS[type].symbol} ${ITEMS[type].name}`,1000);}
function weaponCount(){return Object.keys(UPGRADES).filter(k=>UPGRADES[k].kind==='weapon'&&state.levels[k]>0).length;}
function abilityCount(){return Object.keys(UPGRADES).filter(k=>UPGRADES[k].kind==='ability'&&state.levels[k]>0).length;}
function availableUpgrades(){return Object.keys(UPGRADES).filter(k=>state.levels[k]<UPGRADES[k].max&&(state.levels[k]>0||(UPGRADES[k].kind==='weapon'?weaponCount()<MAX_WEAPONS:abilityCount()<MAX_ABILITIES)));}
function eligibleEvolutions(){return Object.keys(EVOLUTIONS).filter(key=>state.levels[key]===UPGRADES[key].max&&state.levels[EVOLUTIONS[key].ability]>=3&&!state.evolved[key]);}
function evolveWeapon(key){const evolution=EVOLUTIONS[key];if(!evolution)return null;state.evolved[key]=true;renderLoadout();return {symbol:evolution.symbol,name:evolution.name,desc:`${UPGRADES[key].name}が進化！ ${evolution.desc}`,evolution:true};}
function openChest(){state.paused=true;cancelAnimationFrame(raf);let rewards=[];const evolutions=shuffle(eligibleEvolutions());if(evolutions.length)rewards=[evolveWeapon(evolutions[0])];else rewards=grantRandomUpgrades(2);if(!rewards.length){state.player.hp=state.player.maxHp;rewards=[{symbol:'♥',name:'完全回復',desc:'すべての強化が完成しているためHPを全回復',evolution:false}];}ui.rewardTitle.textContent=rewards.some(r=>r.evolution)?'武器進化！':'宝箱を獲得！';ui.rewardList.replaceChildren();for(const reward of rewards){const item=document.createElement('div');item.className=`reward-item${reward.evolution?' evolution':''}`;item.innerHTML=`<span class="symbol">${reward.symbol}</span><span><strong>${reward.name}</strong><small>${reward.desc}</small></span>`;ui.rewardList.append(item);}ui.reward.hidden=false;}
function closeReward(){ui.reward.hidden=true;if(checkLevelUp())return;state.paused=false;updateUI();lastTime=performance.now();raf=requestAnimationFrame(loop);}
function gainXp(amount){state.xp+=amount;if(!state.paused)checkLevelUp();}
function checkLevelUp(){if(state.xp<state.nextXp||state.ended)return false;state.xp-=state.nextXp;state.level++;state.nextXp=Math.round(24+state.level*13+state.level**1.5);return showUpgrade();}
function showUpgrade(){state.paused=true;cancelAnimationFrame(raf);state.rerolls=1;state.lastChoices=[];const shown=renderUpgradeChoices();if(shown)ui.upgrade.hidden=false;else state.paused=false;return shown;}
function selectUpgradeChoices(excluded=[]){const excludedSet=new Set(excluded);let available=availableUpgrades().filter(k=>!excludedSet.has(k));if(available.length<3)available=availableUpgrades();const owned=shuffle(available.filter(k=>state.levels[k]>0)),fresh=shuffle(available.filter(k=>!state.levels[k])),choices=[];choices.push(...owned.slice(0,2));for(const key of [...fresh,...owned.slice(2)])if(choices.length<3&&!choices.includes(key))choices.push(key);return choices;}
function renderUpgradeChoices(){const available=availableUpgrades();state.lastChoices=selectUpgradeChoices(state.lastChoices);ui.upgradeList.replaceChildren();for(const key of state.lastChoices){const u=UPGRADES[key],button=document.createElement('button');button.type='button';button.className='upgrade-card';button.innerHTML=`<span class="symbol">${u.symbol}</span><span><strong>${u.name}</strong><small>${u.desc}</small></span><em>Lv ${state.levels[key]} → ${state.levels[key]+1}</em>`;button.onclick=()=>chooseUpgrade(key);ui.upgradeList.append(button);}ui.reroll.disabled=state.rerolls===0||available.length<=state.lastChoices.length;ui.reroll.textContent=state.rerolls?'↻ 候補を引き直す（1回）':'↻ 引き直し済み';return state.lastChoices.length>0;}
function rerollUpgrades(){if(!state.rerolls)return;state.rerolls=0;renderUpgradeChoices();}
function applyUpgrade(key){if(!UPGRADES[key]||state.levels[key]>=UPGRADES[key].max)return false;if(!state.levels[key]){if(UPGRADES[key].kind==='weapon'&&weaponCount()>=MAX_WEAPONS)return false;if(UPGRADES[key].kind==='ability'&&abilityCount()>=MAX_ABILITIES)return false;}state.levels[key]++;if(key==='vitality'){state.player.maxHp+=20;state.player.hp=Math.min(state.player.maxHp,state.player.hp+35);}renderLoadout();return true;}
function chooseUpgrade(key){applyUpgrade(key);ui.upgrade.hidden=true;if(checkLevelUp())return;state.paused=false;updateUI();lastTime=performance.now();raf=requestAnimationFrame(loop);}
function grantRandomUpgrades(count){const rewards=[];for(let i=0;i<count;i++){const available=availableUpgrades(),owned=available.filter(k=>state.levels[k]>0),pool=owned.length?owned:available;if(!pool.length)break;const key=pool[Math.floor(Math.random()*pool.length)],before=state.levels[key];if(applyUpgrade(key))rewards.push({symbol:UPGRADES[key].symbol,name:UPGRADES[key].name,desc:`Lv ${before} → Lv ${state.levels[key]}`,evolution:false});}return rewards;}
function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
function burst(x,y,color,count){for(let i=0;i<count&&state.particles.length<MAX_PARTICLES;i++){const a=Math.random()*Math.PI*2,s=35+Math.random()*100;state.particles.push(Object.assign(particlePool.pop()||{},{x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,color,life:.35+Math.random()*.35}));}}
function ring(x,y,maxR,color){if(state.rings.length<20)state.rings.push({x,y,r:10,maxR,color,life:.55});}
function updateEffects(dt){for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.life-=dt;}for(const f of state.floaters){f.y-=28*dt;f.life-=dt;}for(const r of state.rings){r.r+=(r.maxR-r.r)*Math.min(1,dt*9);r.life-=dt;}state.particles=state.particles.filter(p=>{if(p.life>0)return true;particlePool.push(p);return false;});state.floaters=state.floaters.filter(f=>f.life>0).slice(-100);state.rings=state.rings.filter(r=>r.life>0);}
function draw(){const {w,h}=screen(),p=state.player,shake=state.screenShake?5:0,ox=w/2-p.x+(Math.random()-.5)*shake,oy=h/2-p.y+(Math.random()-.5)*shake;ctx.clearRect(0,0,w,h);drawGround(w,h,ox,oy);for(const orb of state.orbs)drawOrb(orb,ox,oy);for(const drop of state.drops)drawDrop(drop,ox,oy);for(const ringEffect of state.rings){ctx.globalAlpha=Math.max(0,ringEffect.life/.55);ctx.strokeStyle=ringEffect.color;ctx.lineWidth=4;ctx.beginPath();ctx.arc(ringEffect.x+ox,ringEffect.y+oy,ringEffect.r,0,Math.PI*2);ctx.stroke();}ctx.globalAlpha=1;for(const shot of state.projectiles){ctx.beginPath();ctx.arc(shot.x+ox,shot.y+oy,shot.radius,0,Math.PI*2);ctx.fillStyle=shot.color;ctx.shadowColor=shot.color;ctx.shadowBlur=13;ctx.fill();}ctx.shadowBlur=0;for(const e of state.enemies)drawEnemy(e,e.x+ox,e.y+oy);drawWeapons(w,h);drawPlayer(w/2,h/2,p);for(const particle of state.particles){ctx.globalAlpha=Math.min(1,particle.life*3);ctx.fillStyle=particle.color;ctx.fillRect(particle.x+ox-2,particle.y+oy-2,4,4);}for(const f of state.floaters){ctx.globalAlpha=Math.min(1,f.life*3);ctx.fillStyle=f.color;ctx.font='800 14px system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x+ox,f.y+oy);}ctx.globalAlpha=1;if(state.freeze>0){ctx.fillStyle='#86dfff18';ctx.fillRect(0,0,w,h);}}
function drawGround(w,h,ox,oy){ctx.fillStyle='#090b1d';ctx.fillRect(0,0,w,h);const grid=64,startX=((ox%grid)+grid)%grid,startY=((oy%grid)+grid)%grid;ctx.strokeStyle='#5e4a8522';ctx.lineWidth=1;for(let x=startX;x<w;x+=grid){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke();}for(let y=startY;y<h;y+=grid){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke();}ctx.fillStyle='#7d5daa18';for(let x=startX;x<w;x+=grid)for(let y=startY;y<h;y+=grid){ctx.beginPath();ctx.arc(x,y,2,0,Math.PI*2);ctx.fill();}}
function drawOrb(orb,ox,oy){ctx.save();ctx.translate(orb.x+ox,orb.y+oy);ctx.rotate(state.time*2);ctx.fillStyle='#8d74ff';ctx.shadowColor='#b9a7ff';ctx.shadowBlur=12;ctx.fillRect(-5,-5,10,10);ctx.restore();}
function drawDrop(drop,ox,oy){const item=ITEMS[drop.type];ctx.save();ctx.translate(drop.x+ox,drop.y+oy);ctx.fillStyle='#100a22';ctx.strokeStyle=item.color;ctx.lineWidth=2;ctx.shadowColor=item.color;ctx.shadowBlur=12;ctx.beginPath();ctx.arc(0,0,14,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.fillStyle=item.color;ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(item.symbol,0,1);ctx.restore();}
function drawWeapons(w,h){const l=state.levels;if(l.fire){ctx.strokeStyle=state.evolved.fire?'#ffd05bbb':'#ff703f88';ctx.lineWidth=3+l.fire+(state.evolved.fire?3:0);ctx.beginPath();ctx.arc(w/2,h/2,weaponRange('fire'),0,Math.PI*2);ctx.stroke();}if(l.orbit){const blades=1+l.orbit+(state.evolved.orbit?2:0),range=weaponRange('orbit');for(let i=0;i<blades;i++){const a=state.time*(state.evolved.orbit?2.8:2.2)+i*Math.PI*2/blades,x=w/2+Math.cos(a)*range,y=h/2+Math.sin(a)*range;ctx.save();ctx.translate(x,y);ctx.rotate(a*2);ctx.fillStyle=state.evolved.orbit?'#ffe893':'#aeefff';ctx.shadowColor=state.evolved.orbit?'#ffd76a':'#5bddff';ctx.shadowBlur=10;ctx.fillRect(state.evolved.orbit?-14:-10,-4,state.evolved.orbit?28:20,8);ctx.restore();}}}
function drawPlayer(x,y,p){ctx.save();ctx.translate(x,y);if(p.invulnerable&&Math.floor(state.time*18)%2)ctx.globalAlpha=.35;ctx.shadowColor='#a982ff';ctx.shadowBlur=18;ctx.fillStyle='#6f4cc6';ctx.beginPath();ctx.arc(0,0,p.radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#eaddff';ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(11,10);ctx.lineTo(0,6);ctx.lineTo(-11,10);ctx.closePath();ctx.fill();ctx.restore();}
function drawEnemy(e,x,y){ctx.save();ctx.translate(x,y);ctx.shadowColor=e.champion?'#ffd76a':e.color;ctx.shadowBlur=e.type==='boss'?20:e.champion?16:7;ctx.fillStyle=e.slow>0?'#75cde4':e.color;ctx.beginPath();if(e.type==='bat'){ctx.moveTo(-e.radius,0);ctx.lineTo(-4,-8);ctx.lineTo(0,3);ctx.lineTo(4,-8);ctx.lineTo(e.radius,0);ctx.lineTo(0,e.radius);ctx.closePath();}else ctx.arc(0,0,e.radius,0,Math.PI*2);ctx.fill();if(e.champion){ctx.strokeStyle='#ffe477';ctx.lineWidth=3;ctx.stroke();}ctx.shadowBlur=0;ctx.fillStyle='#170c20';ctx.fillRect(-7,-3,4,4);ctx.fillRect(3,-3,4,4);if(e.type==='elite'||e.type==='boss'||e.champion){ctx.fillStyle='#240b15';ctx.fillRect(-e.radius,-e.radius-9,e.radius*2,5);ctx.fillStyle=e.champion?'#ffe477':'#ffdf72';ctx.fillRect(-e.radius,-e.radius-9,e.radius*2*Math.max(0,e.hp/e.maxHp),5);}ctx.restore();}
function renderLoadout(){ui.loadout.replaceChildren();for(const key of Object.keys(UPGRADES).filter(k=>state.levels[k])){const evolved=state.evolved[key]&&EVOLUTIONS[key],data=evolved||UPGRADES[key],s=document.createElement('span');if(evolved)s.classList.add('evolved');s.textContent=`${data.symbol} ${data.name} `;const b=document.createElement('b');b.textContent=evolved?'進化':`Lv${state.levels[key]}`;s.append(b);if(UPGRADES[key].kind==='weapon')s.setAttribute('aria-label',`${data.name}、${evolved?'進化済み、':''}射程${Math.round(weaponRange(key))}`);ui.loadout.append(s);}}
function updateUI(){const p=state.player,remaining=Math.max(0,Math.ceil(GAME_LENGTH-state.time)),minutes=Math.floor(remaining/60),seconds=remaining%60;ui.level.textContent=state.level;ui.time.textContent=`${minutes}:${String(seconds).padStart(2,'0')}`;ui.kills.textContent=state.kills;ui.score.textContent=Math.floor(state.score+state.time*5);ui.hp.style.width=`${p.hp/p.maxHp*100}%`;ui.hpText.textContent=`${Math.ceil(p.hp)} / ${p.maxHp}`;ui.xp.style.width=`${state.xp/state.nextXp*100}%`;ui.xpText.textContent=`${Math.floor(state.xp)} / ${state.nextXp} XP`;}
function showAlert(text,duration){ui.bossAlert.textContent=text;ui.bossAlert.hidden=false;setTimeout(()=>ui.bossAlert.hidden=true,duration);}
function finish(success){if(state.ended)return;state.ended=true;state.running=false;cancelAnimationFrame(raf);const total=Math.floor(state.score+state.time*5+(success?5000:0)),best=Math.max(total,Number(localStorage.getItem('night-survivor-best')||0));localStorage.setItem('night-survivor-best',best);ui.best.textContent=best;document.querySelector('#result-label').textContent=success?'NIGHT CLEARED':'GAME OVER';document.querySelector('#result-title').textContent=success?'夜明けを迎えた！':'夜に飲まれた…';document.querySelector('#result-summary').textContent=`レベル ${state.level}・撃破 ${state.kills}体（エリート ${state.eliteKills}体）・スコア ${total}`;ui.result.hidden=false;updateUI();}
function pointerVector(event){const rect=arena.getBoundingClientRect(),x=event.clientX-rect.left,y=event.clientY-rect.top,dx=x-stickOrigin.x,dy=y-stickOrigin.y,d=Math.hypot(dx,dy),limit=38,nx=d?dx/d:0,ny=d?dy/d:0,strength=Math.min(1,d/limit),move=Math.min(limit,d);input.x=nx*strength;input.y=ny*strength;ui.stick.firstElementChild.style.transform=`translate(${nx*move}px,${ny*move}px)`;}
arena.addEventListener('pointerdown',event=>{if(!state.running||state.paused||state.ended)return;pointerId=event.pointerId;arena.setPointerCapture(pointerId);const rect=arena.getBoundingClientRect();stickOrigin={x:event.clientX-rect.left,y:event.clientY-rect.top};ui.stick.style.left=`${Math.max(8,Math.min(rect.width-100,stickOrigin.x-46))}px`;ui.stick.style.top=`${Math.max(8,Math.min(rect.height-100,stickOrigin.y-46))}px`;ui.stick.style.bottom='auto';ui.stick.classList.add('active');input={x:0,y:0};});
arena.addEventListener('pointermove',event=>{if(event.pointerId===pointerId)pointerVector(event);});
function releasePointer(event){if(event.pointerId!==pointerId)return;pointerId=null;input={x:0,y:0};ui.stick.classList.remove('active');ui.stick.firstElementChild.style.transform='';}
arena.addEventListener('pointerup',releasePointer);arena.addEventListener('pointercancel',releasePointer);
addEventListener('keydown',event=>{const k=event.key.length===1?event.key.toLowerCase():event.key;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(k)){event.preventDefault();keys[k]=true;}if(k==='Escape')togglePause();});addEventListener('keyup',event=>{const k=event.key.length===1?event.key.toLowerCase():event.key;keys[k]=false;});
addEventListener('resize',()=>{resize();draw();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.running&&!state.paused)togglePause(true);});
document.querySelector('#start').onclick=start;ui.pause.onclick=()=>togglePause();document.querySelector('#resume').onclick=()=>togglePause(false);document.querySelector('#again').onclick=reset;document.querySelector('#reward-close').onclick=closeReward;ui.reroll.onclick=rerollUpgrades;
reset();
