const F=['🀄','🀅','🀆','🀀','🀁','🀂','🀃','🀇','🀈','🀉','🀐','🀑','🀒','🀙','🀚','🀛','🀢','🀥'];
const CFG={easy:{dims:[[6,4],[4,2],[2,2]],mult:1},normal:{dims:[[8,6],[4,4],[2,2],[2,1],[2,1]],mult:1.5},hard:{dims:[[10,7],[6,4],[4,2],[2,1],[2,1],[2,1]],mult:2}};
let tiles=[],selected=null,history=[],score=0,seconds=0,timer,started=false,locked=false,lastMatch=0,combo=0,level=localStorage.getItem('mahjong-level')||'easy';
const board=document.querySelector('#board'),msg=document.querySelector('#message'),difficulty=document.querySelector('#difficulty');difficulty.value=level;
const dynamicStyle=document.createElement('style');dynamicStyle.textContent='.difficulty{display:flex;justify-content:space-between;align-items:center;margin:8px 0;color:#c9d8ce}.difficulty select{min-height:38px;border:1px solid #789586;border-radius:9px;background:#173a2a;color:#fff;padding:4px 8px}.tile{transform:none!important}.face.back{color:#86aa98;background:repeating-linear-gradient(45deg,#193f30,#193f30 8px,#225440 8px,#225440 16px);font-size:min(30cqw,34cqh);text-shadow:none}.tile.reveal .face{animation:reveal .38s ease-out}@keyframes reveal{from{transform:rotateY(90deg);filter:brightness(1.8)}to{transform:rotateY(0)}}';document.head.append(dynamicStyle);
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function positions(){const dims=CFG[level].dims,p=[],root=dims[0],mirror=Math.random()<.5,flip=Math.random()<.5;let parent={x2:0,y2:0,w:root[0],h:root[1]};dims.forEach(([w,h],z)=>{let x2=0,y2=0;if(z){const xs=[];for(let x=parent.x2-1;x<=parent.x2+(parent.w-w)*2+1;x+=2)if(x>=0&&x+w*2<=root[0]*2)xs.push(x);x2=shuffle(xs)[0];y2=parent.y2+2*Math.floor(Math.random()*(parent.h-h+1))}for(let r=0;r<h;r++)for(let c=0;c<w;c++){let px2=x2+c*2,py2=y2+r*2;if(mirror)px2=root[0]*2-2-px2;if(flip)py2=root[1]*2-2-py2;p.push({x2:px2,y2:py2,z})}parent={x2,y2,w,h}});board.dataset.cols=root[0];board.dataset.rows=root[1];return p}
function overlap(a,b){return a.x2<b.x2+2&&a.x2+2>b.x2&&a.y2<b.y2+2&&a.y2+2>b.y2}
function free(t,list=tiles){if(!t.active)return false;const a=list.filter(x=>x.active&&x.id!==t.id),above=a.some(x=>x.z>t.z&&overlap(t,x)),vertical=x=>t.y2<x.y2+2&&t.y2+2>x.y2,left=a.some(x=>x.z===t.z&&vertical(x)&&x.x2<t.x2&&x.x2+2>=t.x2),right=a.some(x=>x.z===t.z&&vertical(x)&&x.x2>t.x2&&t.x2+2>=x.x2);return !above&&(!left||!right)}
function assign(list){const sim=list.map(t=>({...t,active:true})),pairs=[];while(sim.some(t=>t.active)){const c=shuffle(sim.filter(t=>free(t,sim)));if(c.length<2)return false;c[0].active=c[1].active=false;pairs.push([c[0].id,c[1].id])}shuffle(pairs).forEach((p,i)=>p.forEach(id=>list.find(t=>t.id===id).face=F[i%F.length]));return true}
function family(f){const n=f.codePointAt(0);if(f==='🀄')return'dragon';if(n>=0x1f007&&n<=0x1f00f)return'man';if(n>=0x1f010&&n<=0x1f018)return'bamboo';if(n>=0x1f019&&n<=0x1f021)return'dot';return'honor'}
function newGame(){clearInterval(timer);do{tiles=positions().map((p,id)=>({...p,id,active:true,face:'',revealed:false}))}while(!assign(tiles));selected=null;history=[];score=seconds=combo=0;started=locked=false;document.querySelector('#dialog').hidden=true;document.querySelector('#board-id').textContent=`山 #${Math.floor(100000+Math.random()*900000)}`;msg.textContent='表向きの牌を選んでください';render()}
function render(){board.querySelectorAll('.tile').forEach(e=>e.remove());const cols=+board.dataset.cols,rows=+board.dataset.rows,gridW=90,gridH=84,tileW=gridW/cols,tileH=gridH/rows;board.style.aspectRatio=Math.max(1.05,cols/rows);tiles.filter(t=>t.active).forEach(t=>{const avail=free(t),reveal=avail&&!t.revealed;if(avail)t.revealed=true;const b=document.createElement('button');b.dataset.id=t.id;b.dataset.layer=t.z;b.className=`tile ${avail?'free':'blocked'}${selected===t.id?' selected':''}${reveal?' reveal':''}`;b.style.width=`${tileW}%`;b.style.height=`${tileH}%`;b.style.left=`${5+t.x2*tileW/2}%`;b.style.top=`${8+t.y2*tileH/2}%`;b.style.setProperty('--z',10+t.z*20+t.y2/2);b.style.setProperty('--side-depth',`${4+t.z*.8}px`);b.style.setProperty('--shadow-y',`${8+t.z*1.5}px`);b.style.setProperty('--shadow-blur',`${7+t.z}px`);b.innerHTML=avail?`<span class="face ${family(t.face)}">${t.face}</span>`:'<span class="face back">◆</span>';b.onclick=()=>choose(t,b);board.append(b)});document.querySelector('#remaining').textContent=tiles.filter(t=>t.active).length;document.querySelector('#score').textContent=score;showTime();document.querySelector('#undo').disabled=!history.length||locked}
function showTime(){document.querySelector('#time').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}function start(){if(!started){started=true;timer=setInterval(()=>{seconds++;showTime()},1000)}}
function choose(t,e){if(locked)return;start();if(!free(t)){e.classList.add('shake');msg.textContent='まだ取れません';setTimeout(()=>e.classList.remove('shake'),320);return}if(selected===null){selected=t.id;render();return}const a=tiles.find(x=>x.id===selected);if(a.id===t.id){selected=null;render();return}if(a.face!==t.face){selected=t.id;msg.textContent='図柄が違います';render();return}locked=true;history.push({ids:[a.id,t.id],score});combo=Date.now()-lastMatch<2500?combo+1:1;lastMatch=Date.now();const gain=Math.round(100*combo*CFG[level].mult);score+=gain;selected=null;const pair=[a,t].map(x=>board.querySelector(`[data-id="${x.id}"]`));pair.forEach(x=>x.classList.add('matched'));burst(pair,gain);setTimeout(()=>{a.active=t.active=false;locked=false;render();if(!tiles.some(x=>x.active))complete()},520)}
function burst(pair,g){const br=board.getBoundingClientRect(),r=pair.map(e=>e.getBoundingClientRect()),x=(r[0].left+r[0].right+r[1].left+r[1].right)/4-br.left,y=(r[0].top+r[0].bottom+r[1].top+r[1].bottom)/4-br.top,add=c=>{const e=document.createElement('i');e.className=c;e.style.left=x+'px';e.style.top=y+'px';board.append(e);setTimeout(()=>e.remove(),800);return e};add('match-ring');const p=add('match-points');p.textContent='+'+g;for(let i=0;i<12;i++){const s=add('match-spark');s.style.setProperty('--a',i*30+'deg');s.style.setProperty('--d',45+Math.random()*30+'px')}}
function hint(){if(locked)return;const a=tiles.filter(t=>free(t));for(let i=0;i<a.length;i++){const b=a.slice(i+1).find(x=>x.face===a[i].face);if(b){[a[i],b].forEach(x=>board.querySelector(`[data-id="${x.id}"]`).classList.add('hint'));return}}msg.textContent='シャッフルしてください'}function undo(){if(locked)return;const h=history.pop();if(h){h.ids.forEach(id=>tiles.find(t=>t.id===id).active=true);score=h.score;render()}}function reshuffle(){if(!locked&&assign(tiles.filter(t=>t.active)))render()}function complete(){clearInterval(timer);document.querySelector('#result').textContent=`${seconds}秒・${score}点`;document.querySelector('#dialog').hidden=false}
difficulty.onchange=()=>{level=difficulty.value;localStorage.setItem('mahjong-level',level);newGame()};document.querySelector('#hint').onclick=hint;document.querySelector('#undo').onclick=undo;document.querySelector('#shuffle').onclick=reshuffle;document.querySelector('#restart').onclick=newGame;document.querySelector('#again').onclick=newGame;newGame();
