const F=['🀄','🀅','🀆','🀀','🀁','🀂','🀃','🀇','🀈','🀉','🀐','🀑','🀒','🀙','🀚','🀛','🀢','🀥'];let tiles=[],selected=null,history=[],score=0,seconds=0,timer,started=false,lastMatch=0,combo=0,soundOn=true;const board=document.querySelector('#board'),msg=document.querySelector('#message');
function positions(){const p=[];for(let y=0;y<4;y++)for(let x=0;x<6;x++)p.push({x,y,z:0});for(let y=1;y<3;y++)for(let x=1;x<5;x++)p.push({x,y,z:1});for(let y=1;y<3;y++)for(let x=2;x<4;x++)p.push({x,y,z:2});return p}function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function free(t,list=tiles){if(!t.active)return false;const a=list.filter(x=>x.active&&x.id!==t.id),above=a.some(x=>x.z>t.z&&Math.abs(x.x-t.x)<.8&&Math.abs(x.y-t.y)<.8),left=a.some(x=>x.z===t.z&&x.y===t.y&&x.x===t.x-1),right=a.some(x=>x.z===t.z&&x.y===t.y&&x.x===t.x+1);return !above&&(!left||!right)}
function assign(list){const sim=list.map(t=>({...t,active:true})),pairs=[];while(sim.some(t=>t.active)){const choices=shuffle(sim.filter(t=>free(t,sim)));if(choices.length<2)return false;choices[0].active=choices[1].active=false;pairs.push([choices[0].id,choices[1].id])}shuffle(pairs).forEach((p,i)=>p.forEach(id=>list.find(t=>t.id===id).face=F[i%F.length]));return true}
function newGame(){clearInterval(timer);do{tiles=positions().map((p,id)=>({...p,id,active:true,face:''}))}while(!assign(tiles));selected=null;history=[];score=seconds=combo=0;started=false;document.querySelector('#dialog').hidden=true;msg.textContent='左右が空いている牌を選んでください';render()}
function render(){board.querySelectorAll('.tile').forEach(e=>e.remove());tiles.filter(t=>t.active).forEach(t=>{const b=document.createElement('button');b.dataset.id=t.id;b.className=`tile ${free(t)?'free':'blocked'}${selected===t.id?' selected':''}`;b.style.setProperty('--tx',`${t.x*102+t.z*7}%`);b.style.setProperty('--ty',`${t.y*100-t.z*7}%`);b.style.setProperty('--z',10+t.z*20+t.y);b.innerHTML=`<span class="face">${t.face}</span>`;b.onclick=()=>choose(t,b);board.append(b)});document.querySelector('#remaining').textContent=tiles.filter(t=>t.active).length;document.querySelector('#score').textContent=score;showTime();document.querySelector('#undo').disabled=!history.length}function showTime(){document.querySelector('#time').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`}function start(){if(started)return;started=true;timer=setInterval(()=>{seconds++;showTime()},1000)}
function choose(t,el){start();if(!free(t)){el.classList.add('shake');msg.textContent='その牌はふさがっています';setTimeout(()=>el.classList.remove('shake'),320);tone(120);return}if(selected===t.id){selected=null;render();return}if(selected===null){selected=t.id;msg.textContent='同じ牌をもう1枚選んでください';render();return}const first=tiles.find(x=>x.id===selected);if(first.face!==t.face){selected=t.id;msg.textContent='図柄が違います';render();tone(180);return}history.push({ids:[first.id,t.id],score});combo=Date.now()-lastMatch<2500?combo+1:1;lastMatch=Date.now();score+=100*combo;selected=null;[first,t].forEach(x=>board.querySelector(`[data-id="${x.id}"]`).classList.add('matched'));showCombo();tone(520+combo*60);if(navigator.vibrate)navigator.vibrate(22);setTimeout(()=>{first.active=t.active=false;msg.textContent='ペア成立！';render();if(!tiles.some(x=>x.active))complete()},480)}
function showCombo(){const e=document.querySelector('#combo');e.textContent=combo>1?`${combo} COMBO!`:'+100';e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}function hint(){const a=tiles.filter(t=>free(t));let pair;for(let i=0;i<a.length&&!pair;i++){const mate=a.slice(i+1).find(t=>t.face===a[i].face);if(mate)pair=[a[i],mate]}if(!pair){msg.textContent='取れるペアがありません。シャッフルしてください';return}pair.forEach(t=>board.querySelector(`[data-id="${t.id}"]`).classList.add('hint'));msg.textContent='光っている牌がペアです'}
function undo(){const h=history.pop();if(!h)return;h.ids.forEach(id=>tiles.find(t=>t.id===id).active=true);score=h.score;selected=null;msg.textContent='1手戻しました';render()}function reshuffle(){const a=tiles.filter(t=>t.active);if(assign(a)){selected=null;score=Math.max(0,score-50);msg.textContent='残り牌をシャッフルしました';render()}}function complete(){clearInterval(timer);confetti();setTimeout(()=>{document.querySelector('#result').textContent=`${seconds}秒・${score}点`;document.querySelector('#dialog').hidden=false},650)}
function confetti(){const box=document.querySelector('#confetti');for(let i=0;i<55;i++){const p=document.createElement('i');p.style.setProperty('--c',`hsl(${Math.random()*360} 85% 60%)`);p.style.setProperty('--dx',`${(Math.random()-.5)*650}px`);p.style.setProperty('--dy',`${Math.random()*380-100}px`);box.append(p)}setTimeout(()=>box.replaceChildren(),1700)}function tone(f){if(!soundOn)return;const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.frequency.value=f;g.gain.setValueAtTime(.05,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+.12);o.connect(g).connect(c.destination);o.start();o.stop(c.currentTime+.12)}
document.querySelector('#hint').onclick=hint;document.querySelector('#undo').onclick=undo;document.querySelector('#shuffle').onclick=reshuffle;document.querySelector('#restart').onclick=newGame;document.querySelector('#again').onclick=newGame;document.querySelector('#sound').onclick=e=>{soundOn=!soundOn;e.currentTarget.textContent=soundOn?'♪':'×'};newGame();
